name: Playwright Tests
on:
  push:
    branches: [ workflow-example ]
  pull_request:
    branches: [ workflow-example ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    # - name: Install dependencies
    #   run: npm ci
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   timeout-minutes: 7
    #   run: npx playwright test
    # - uses: actions/upload-artifact@v4
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30

    # - name: Get composite run steps repository
    #   if: always()
    #   uses: actions/checkout@v4
    #   with:
    #     repository: Sohill-Patel/get-ac-coverage
    #     # Select revision
    #     ref: 'main'
    #     # Personal access token to check out private repository
    #     token: ${{ secrets.PAT_TOKEN }}
    #     # Indicate where to check action out to
    #     path: composite/get-ac-coverage
    
    - id: Drop-ref
      if: always()
      run: echo The event is ${{github.event_name}} and the base ref is ${{github.base_ref}} and the ref is ${{github.ref}}
      shell: bash

    - id: foo
      if: always() && github.event_name == 'push'
      # run: cd composite/get-ac-coverage && ls -ltr
      run: echo It ran again!
      shell: bash
      # uses: ./composite/get-ac-coverage/
      # with:
      #   FILENAME: "testreport"
      #   NOTION-TOKEN: "test-token"
      #   NOTION-DB: "test-db"
        

