name: Run E2E tests

on:
  workflow_dispatch:
  push:
  pull_request:
  # schedule:
  #     - cron "00 00 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: Sohill-Patel
          repo: Sohill-Patel/trigger-workflow-test
          github_token: ${{ secrets.PAT_TOKEN }}
          ref: workflow-example
          workflow_file_name: example.yml